export default {
    GET_IMAGES: 'GET_IMAGES',
    GET_ALBUM_IMAGES: 'GET_ALBUM_IMAGES',
    GET_ALBUMS: 'GET_ALBUMS',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    GET_ITEMS_FROM_LOCAL_STORAGE: 'GET_ITEMS_FROM_LOCAL_STORAGE',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES' 
}